# Generated by Django 4.0.4 on 2022-05-03 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название группы')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала учебы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата завершения учебы')),
                ('is_end', models.BooleanField(default=False, verbose_name='Обучение закончено')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='courses.course', verbose_name='Название курса')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'type': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Закончил обучение')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom', verbose_name='Группа')),
                ('student', models.ForeignKey(limit_choices_to={'type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Учебная группа ученика',
                'verbose_name_plural': 'Учебные группы учеников',
                'ordering': ['classroom'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения занятия')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='classrooms.classroom', verbose_name='Группа')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.lesson', verbose_name='Урок')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на домашнее задание')),
                ('need_to_fix', models.BooleanField(default=False, verbose_name='Требует доработки')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Работа выполнена верно')),
                ('date_of_publication', models.DateField(auto_now_add=True, verbose_name='Дата сдачи работы')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classrooms.schedule', verbose_name='Урок')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'type': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.AddConstraint(
            model_name='studentclassroom',
            constraint=models.UniqueConstraint(fields=('classroom', 'student'), name='unique_student_classroom'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('student', 'schedule'), name='unique_student_schedule'),
        ),
    ]
